_wandb:
    value:
        cli_version: 0.22.1
        e:
            hsm2dr50jmeh2ccvqa2zpru57f7ac9tr:
                codePath: q2_2021389_HW1.ipynb
                codePathLocal: q2_2021389_HW1.ipynb
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "368755027968"
                        used: "81216479232"
                email: ganeev21389@iiitd.ac.in
                executable: /bin/python
                git:
                    commit: 8875089d0d65ddfbf347d1913941389a7beb7561
                    remote: https://github.com/ganeevsingh18/CV_assignment1.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-c925a2bc-c7e8-07e3-b691-ec1808032b61
                host: ganeev-Predator-PH315-55
                memory:
                    total: "16456015872"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: /home/ganeev/Desktop/ComputerVision/CV_assignment1/q2_2021389_HW1.ipynb
                python: CPython 3.10.12
                root: /home/ganeev/Desktop/ComputerVision/CV_assignment1
                startedAt: "2025-10-08T04:00:37.765121Z"
                writerId: hsm2dr50jmeh2ccvqa2zpru57f7ac9tr
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 2
                - 13
            "4": 3.10.12
            "5": 0.22.1
            "8":
                - 1
            "12": 0.22.1
            "13": linux-x86_64
